name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER_ID }}
          password: ${{ secrets.DOCKER_ACCESS_KEY }}
      - name: Push to Docker Hub(specified version)
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kazuki0529/asciidoctor-cjk:${{ github.event.release.tag_name }}
      - name: Push to Docker Hub(latest)
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kazuki0529/asciidoctor-cjk:latest
